swagger: '2.0'
info: 
  description: UBC backend API
  version: '1.0.0'
  title: 'UBC API'
basePath: '/api/v1'
schemes:
  - http
  - https
definitions:
  PingResponse:
    type: 'object'
paths:
  /image/{imageId}:
    get:
      operationId: 'getImage'
      parameters:
        - name: imageId
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: 'uploadImage'
      parameters:
        - name: imageId
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /gallery:
    get:
      operationId: listGallary
      responses:
        200:
          description: OK
    post:
      operationId: createGallery
      responses:
        200:
          description: OK
  /gallery/{galleryId}:
    get:
      operationId: getGallary
      parameters:
        - name: imageId
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteGallery
      parameters:
        - name: imageId
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
            
