swagger: '2.0'
info: 
  description: UBC backend API
  version: '1.0.0'
  title: 'UBC API'
basePath: '/api/v1'
schemes:
  - http
  - https
definitions:
  PingResponse:
    type: 'object'
paths:
  /image/{id}:
    get:
      operationId: 'getImage'
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: 'uploadImage'
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /gallery:
    get:
      operationId: listGallery
      responses:
        200:
          description: OK
    post:
      operationId: saveGallery
      responses:
        200:
          description: OK
  /gallery/{id}:
    get:
      operationId: getGallery
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteGallery
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /poster:
    get:
      operationId: listPoster
      responses:
        200:
          description: OK
    post:
      operationId: savePoster
      responses:
        200:
          description: OK
  /poster/{id}:
    get:
      operationId: getPoster
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deletePoster
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
            
